---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${STORAGE_CLASS_NAME}
  namespace: "${K8S_NAMESPACE}"
provisioner: esri.com-${DEPLOYMENT_NAME}/nfs
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: relational-data-volume-1
  labels:
    arcgis/type: local
    arcgis/app: postgres
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/relational-data-volume-1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: relational-data-volume-2
  labels:
    arcgis/type: local
    arcgis/app: postgres
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/relational-data-volume-2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-1
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-2
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-3
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-3"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-4
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-4"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-5
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-5"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-6
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-6"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-7
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-7"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-8
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-8"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-9
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-9"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-10
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-10"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-11
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-11"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-data-volume-12
  labels:
    arcgis/type: local
    arcgis/app: minio
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/blob-data-volume-12"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spatiotemporal-data-volume-1
  labels:
    arcgis/type: local
    arcgis/app: elasticsearch
    arcgis/role: master
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/spatiotemporal-data-volume-1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spatiotemporal-data-volume-2
  labels:
    arcgis/type: local
    arcgis/app: elasticsearch
    arcgis/role: master
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/spatiotemporal-data-volume-2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spatiotemporal-data-volume-3
  labels:
    arcgis/type: local
    arcgis/app: elasticsearch
    arcgis/role: master
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/spatiotemporal-data-volume-3"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spatiotemporal-data-volume-4
  labels:
    arcgis/type: local
    arcgis/app: elasticsearch
    arcgis/role: master
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/spatiotemporal-data-volume-4"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spatiotemporal-data-volume-5
  labels:
    arcgis/type: local
    arcgis/app: elasticsearch
    arcgis/role: master
    arcgis/tier: storage
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/spatiotemporal-data-volume-5"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-data-volume
  labels:
    arcgis/type: local
    arcgis/app: ignite
    arcgis/tier: storage
  annotations:
    storageClassName: ${STORAGE_CLASS_NAME}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/cache-data-volume"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: queue-data-volume-0
  labels:
    arcgis/type: local
    arcgis/app: rabbitmq
    arcgis/tier: queue
  annotations:
    storageClassName: ${STORAGE_CLASS_NAME}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/queue-data-volume-0"    

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: queue-data-volume-1
  labels:
    arcgis/type: local
    arcgis/app: rabbitmq
    arcgis/tier: queue
  annotations:
    storageClassName: ${STORAGE_CLASS_NAME}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/queue-data-volume-1"
    
---    

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharing-volume-1
  labels:
    arcgis/type: local
    arcgis/app: sharing
    arcgis/tier: api
  annotations:
    storageClassName: ${STORAGE_CLASS_NAME}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/sharing-volume-1"

---    

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharing-volume-2
  labels:
    arcgis/type: local
    arcgis/app: sharing
    arcgis/tier: api
  annotations:
    storageClassName: ${STORAGE_CLASS_NAME}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/sharing-volume-2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: metric-api-volume
  labels:
    arcgis/type: local
    arcgis/app: prometheus
    arcgis/tier: storage
  annotations:
    storageClassName: ${STORAGE_CLASS_NAME}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${NFS_SERVER_PATH}/metric-api-volume"
