#RBAC permissions
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ${K8S_NAME_PROMETHEUS_SERVICE_ACCOUNT}
  namespace: "${K8S_NAMESPACE}"
  labels:
    arcgis/app: prometheus
    arcgis/siteName: ${ARCGIS_SITENAME}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${K8S_NAME_PROMETHEUS_ROLE}
  namespace: "${K8S_NAMESPACE}"
  labels:
    arcgis/app: prometheus
    arcgis/siteName: ${ARCGIS_SITENAME}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${K8S_NAME_PROMETHEUS_ROLE_BINDING}
  namespace: "${K8S_NAMESPACE}"
  labels:
    arcgis/app: prometheus
    arcgis/siteName: ${ARCGIS_SITENAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${K8S_NAME_PROMETHEUS_ROLE}
subjects:
  - kind: ServiceAccount
    name: ${K8S_NAME_PROMETHEUS_SERVICE_ACCOUNT}
    namespace: "${K8S_NAMESPACE}"
